export const FETCH_BASKET_PRODUCTS_REQUEST = 'FETCH_BASKET_PRODUCTS_REQUEST';
export const FETCH_BASKET_PRODUCTS_SUCCESS = 'FETCH_BASKET_PRODUCTS_SUCCESS';
export const FETCH_BASKET_PRODUCTS_FAILURE = 'FETCH_BASKET_PRODUCTS_FAILURE';

export const REMOVE_BASKET_PRODUCT_REQUEST = 'REMOVE_BASKET_PRODUCT_REQUEST';
export const REMOVE_BASKET_PRODUCT_SUCCESS = 'REMOVE_BASKET_PRODUCT_SUCCESS';
export const REMOVE_BASKET_PRODUCT_FAILURE = 'REMOVE_BASKET_PRODUCT_FAILURE';

export const ADD_PRODUCT_TO_BASKET_REQUEST = 'ADD_PRODUCT_TO_BASKET_REQUEST';
export const ADD_PRODUCT_TO_BASKET_SUCCESS = 'ADD_PRODUCT_TO_BASKET_SUCCESS';
export const ADD_PRODUCT_TO_BASKET_FAILURE = 'ADD_PRODUCT_TO_BASKET_FAILURE';

export const CHANGE_AMOUNT_IN_BASKET_REQUEST = 'CHANGE_AMOUNT_IN_BASKET_REQUEST';
export const CHANGE_AMOUNT_IN_BASKET_SUCCESS = 'CHANGE_AMOUNT_IN_BASKET_SUCCESS';
export const CHANGE_AMOUNT_IN_BASKET_FAILURE = 'CHANGE_AMOUNT_IN_BASKET_FAILURE';

export const RESET_BASKET_REQUEST = 'RESET_BASKET_REQUEST';
export const RESET_BASKET_SUCCESS = 'RESET_BASKET_SUCCESS';
export const RESET_BASKET_FAILURE = 'RESET_BASKET_FAILURE';

