export const FETCH_CURRENT_PRODUCT_REQUEST = 'FETCH_CURRENT_PRODUCT_REQUEST';
export const FETCH_CURRENT_PRODUCT_SUCCESS = 'FETCH_CURRENT_PRODUCT_SUCCESS';
export const FETCH_CURRENT_PRODUCT_FAILURE = 'FETCH_CURRENT_PRODUCT_FAILURE';

export const FETCH_POPULAR_PRODUCTS_REQUEST = 'FETCH_POPULAR_PRODUCTS_REQUEST';
export const FETCH_POPULAR_PRODUCTS_SUCCESS = 'FETCH_POPULAR_PRODUCTS_SUCCESS';
export const FETCH_POPULAR_PRODUCTS_FAILURE = 'FETCH_POPULAR_PRODUCTS_FAILURE';

export const FETCH_FILTER_PRODUCTS_REQUEST = 'FETCH_FILTER_PRODUCTS_REQUEST';
export const FETCH_FILTER_PRODUCTS_SUCCESS = 'FETCH_FILTER_PRODUCTS_SUCCESS';
export const FETCH_FILTER_PRODUCTS_FAILURE = 'FETCH_FILTER_PRODUCTS_FAILURE';

export const FETCH_SEARCH_PRODUCTS_REQUEST = 'FETCH_SEARCH_PRODUCTS_REQUEST';
export const FETCH_SEARCH_PRODUCTS_SUCCESS = 'FETCH_SEARCH_PRODUCTS_SUCCESS';
export const FETCH_SEARCH_PRODUCTS_FAILURE = 'FETCH_SEARCH_PRODUCTS_FAILURE';

export const FETCH_FULL_SEARCH_PRODUCTS_REQUEST = 'FETCH_FULL_SEARCH_PRODUCTS_REQUEST';
export const FETCH_FULL_SEARCH_PRODUCTS_SUCCESS = 'FETCH_FULL_SEARCH_PRODUCTS_SUCCESS';
export const FETCH_FULL_SEARCH_PRODUCTS_FAILURE = 'FETCH_FULL_SEARCH_PRODUCTS_FAILURE';

